### ISSUE TITLE
include a step-by-step guide

### ISSUE THREAD

**Issue by JakeT23cool** [DASPELLER4/Tomato-Jones-RePackaged#2]
NOW!

**Comment by DASPELLER4** [comment]
<img src="https://i.kym-cdn.com/photos/images/newsfeed/002/247/947/e02.jpg">

**Comment by JakeT23cool** [comment]
<img src="
![image](https://user-images.githubusercontent.com/69044307/147694697-cbff263b-4b0b-4469-aa78-d6c50a87ea39.png)
">

**Comment by JakeT23cool** [comment]
![image](https://user-images.githubusercontent.com/69044307/147694719-50328959-d5b3-4b3e-8dd1-393654b05b24.png)

**Comment by DASPELLER4** [comment]
<img src="https://i.kym-cdn.com/photos/images/newsfeed/002/247/947/e02.jpg">

**Comment by JakeT23cool** [comment]
![image](https://user-images.githubusercontent.com/69044307/147694739-d4edb5e8-1105-43d1-8e55-0521faa45e15.png)

**Comment by DASPELLER4** [comment]
<img src="https://i.kym-cdn.com/photos/images/newsfeed/002/247/947/e02.jpg">

**Comment by DASPELLER4** [comment]
please consider
<img src="https://i.kym-cdn.com/photos/images/newsfeed/002/247/947/e02.jpg">

**Comment by JakeT23cool** [comment]
![image](https://user-images.githubusercontent.com/69044307/147694749-9ba36652-49f2-4b73-828e-576d64435890.png)
![image](https://user-images.githubusercontent.com/69044307/147694750-4fb1084c-dd95-434c-a78a-ad69883bffba.png)
![image](https://user-images.githubusercontent.com/69044307/147694751-01770b0e-30dc-4d21-a7ce-23e19b25d52b.png)
![image](https://user-images.githubusercontent.com/69044307/147694752-45ca0293-79c1-4ff9-acc3-70937bca9a22.png)
![image](https://user-images.githubusercontent.com/69044307/147694754-70939253-b425-4fac-b541-a3bf9de891ad.png)
![image](https://user-images.githubusercontent.com/69044307/147694756-ba1d4709-ea91-4b1b-b4c0-0a8e53b98ece.png)
![image](https://user-images.githubusercontent.com/69044307/147694757-9f26221e-8c00-4a0b-9331-ada7784425a9.png)
![image](https://user-images.githubusercontent.com/69044307/147694763-21b9178e-6cb8-4d8d-84be-c24a6421ddc5.png)
![image](https://user-images.githubusercontent.com/69044307/147694764-816c0628-74f7-4224-bace-8e91e319d879.png)
![image](https://user-images.githubusercontent.com/69044307/147694761-e56604e8-8312-455f-bd27-8d1809b7d401.png)
![image](https://user-images.githubusercontent.com/69044307/147694762-3550d184-98cf-455c-bae5-b88a2cbb6d72.png)
![image](https://user-images.githubusercontent.com/69044307/147694758-93b8fb3b-ef2c-41c9-8984-90c7fa1747ad.png)
![image](https://user-images.githubusercontent.com/69044307/147694759-98103b77-df08-4b3e-83c9-9e6974e63e28.png)
v

**Comment by JakeT23cool** [comment]
![image](https://user-images.githubusercontent.com/69044307/147694790-47029b6a-7d88-43c2-8cb5-cf59ce4d9e7c.png)
![image](https://user-images.githubusercontent.com/69044307/147694791-f947bbc4-ff30-4a58-a282-2cb77312a1cd.png)
![image](https://user-images.githubusercontent.com/69044307/147694796-d4b428e7-fb3f-466f-8a9e-317cc6308838.png)
![image](https://user-images.githubusercontent.com/69044307/147694798-f18bc441-eb89-46d2-9e73-cf8d18fc7b3e.png)
![image](https://user-images.githubusercontent.com/69044307/147694799-1fef4dc6-ef28-4599-be18-ba9ed8bcf51c.png)
![image](https://user-images.githubusercontent.com/69044307/147694793-f37ebfe9-2a4c-4a7c-8e9b-569826001353.png)
![image](https://user-images.githubusercontent.com/69044307/147694792-3e2d9a56-8eed-4c52-89d2-d03b9be429c2.png)
![image](https://user-images.githubusercontent.com/69044307/147694800-c2209eb4-b73e-4906-b4da-748658843e3b.png)
![image](https://user-images.githubusercontent.com/69044307/147694795-41533e10-bb17-419e-916b-7ff2f00a14bc.png)
![image](https://user-images.githubusercontent.com/69044307/147694794-feb459c5-e4e7-44b1-b96e-9feeb969eabd.png)
![image](https://user-images.githubusercontent.com/69044307/147694803-37dea933-2711-4308-b954-8026210bd6b7.png)
![image](https://user-images.githubusercontent.com/69044307/147694801-5938d03a-253f-40f6-b09f-9436aff53dd2.png)
![image](https://user-images.githubusercontent.com/69044307/147694802-485b36a9-9b58-439e-b1ad-6806b5112deb.png)
![image](https://user-images.githubusercontent.com/69044307/147694797-b670949f-cae1-46b2-99fe-b0cd60a9f3ef.png)
![image](https://user-images.githubusercontent.com/69044307/147694804-2b921cc7-e0fa-471b-8497-6009b6d35150.png)
![image](https://user-images.githubusercontent.com/69044307/147694805-c9890fdb-bec1-43d9-a3d7-9cd668c58374.png)
![image](https://user-images.githubusercontent.com/69044307/147694806-1ce34a36-5ce6-4c64-ac18-a7cda0feb732.png)
![image](https://user-images.githubusercontent.com/69044307/147694807-73697431-6a7d-479a-ac39-689156056766.png)
![image](https://user-images.githubusercontent.com/69044307/147694808-c500ccd3-633e-4f69-9c0f-c3b0ead32062.png)
![image](https://user-images.githubusercontent.com/69044307/147694811-ace0ac52-fb51-4d1e-97cd-6947c010c7db.png)
![image](https://user-images.githubusercontent.com/69044307/147694812-888b9700-d979-4525-ad2a-b7affab71076.png)
![image](https://user-images.githubusercontent.com/69044307/147694813-93658520-f9f1-4d24-9cf2-a465a9f2761d.png)
![image](https://user-images.githubusercontent.com/69044307/147694814-47ec27d1-cede-4a5b-91e8-b1d6f19d5420.png)
![image](https://user-images.githubusercontent.com/69044307/147694809-7a708a80-64a8-4334-8245-8a54d518fa0d.png)
![image](https://user-images.githubusercontent.com/69044307/147694815-54079fc1-61eb-4c77-b5ea-9a5bb96c5004.png)
![image](https://user-images.githubusercontent.com/69044307/147694816-5dca3435-d0a0-49b4-9148-0e796ee43063.png)
![image](https://user-images.githubusercontent.com/69044307/147694817-3ac9a7d1-0dd4-4181-ac8e-32065bc716c5.png)
![image](https://user-images.githubusercontent.com/69044307/147694818-6fbf0214-e432-431f-a0d1-55cbf2d696fd.png)
![image](https://user-images.githubusercontent.com/69044307/147694819-64cc1596-9468-404d-855a-7b369b8250ac.png)
![image](https://user-images.githubusercontent.com/69044307/147694820-89fb8d01-6d3e-4072-96bc-256e5fcaf8e4.png)
![image](https://user-images.githubusercontent.com/69044307/147694821-35450661-fbb0-464f-98a7-afcd59e45a57.png)
![image](https://user-images.githubusercontent.com/69044307/147694822-c0be98ee-db73-4fa1-8c47-40cd74b1adf6.png)
![image](https://user-images.githubusercontent.com/69044307/147694823-a0fffd8b-d36c-4042-9a85-4e5e26afef23.png)
![image](https://user-images.githubusercontent.com/69044307/147694824-86d2aada-5a50-440f-82dc-6ee1ac29823e.png)
![image](https://user-images.githubusercontent.com/69044307/147694825-1f5464de-85a2-4d3c-bc96-ab155086d420.png)
![image](https://user-images.githubusercontent.com/69044307/147694826-f2063782-845e-4ec1-8af1-0ae91f405a47.png)
![image](https://user-images.githubusercontent.com/69044307/147694827-563f8c4a-5940-4986-8f89-d7aaeb3adf12.png)
![image](https://user-images.githubusercontent.com/69044307/147694828-67a9fb8a-8ca8-4274-8d40-1a04abb0d5d9.png)
![image](https://user-images.githubusercontent.com/69044307/147694829-c593f419-9f1f-493a-8f0d-d55e0140911e.png)
![image](https://user-images.githubusercontent.com/69044307/147694830-956076f6-0958-415a-b045-a7bda8d044fb.png)
![image](https://user-images.githubusercontent.com/69044307/147694831-d8afe367-c782-40ca-b265-803384cbfad7.png)
![image](https://user-images.githubusercontent.com/69044307/147694832-2dec7e99-a1b3-4cb4-8c14-77e342b0180a.png)
![image](https://user-images.githubusercontent.com/69044307/147694833-447278e2-80ea-472b-9f49-a174ae601f69.png)
![image](https://user-images.githubusercontent.com/69044307/147694834-52bfd833-7caf-4b42-a0ac-f1efb5c74bd6.png)
![image](https://user-images.githubusercontent.com/69044307/147694835-7ce93377-2e1a-44d1-bc9e-5f317ec1519c.png)
![image](https://user-images.githubusercontent.com/69044307/147694836-eae0f0a4-bcfd-4d03-8d62-94f018afc43e.png)
![image](https://user-images.githubusercontent.com/69044307/147694837-78ee9c1c-4adc-488f-84f8-cb03cc2c1535.png)
![image](https://user-images.githubusercontent.com/69044307/147694839-4f3ef82f-4cc5-491b-a451-c353ddb501ea.png)
![image](https://user-images.githubusercontent.com/69044307/147694840-c61b53bd-8e53-4461-9a97-33c46172b306.png)
![image](https://user-images.githubusercontent.com/69044307/147694841-4b2f5d27-fcfd-4806-b7d2-2c9f845311e8.png)
![image](https://user-images.githubusercontent.com/69044307/147694843-c0f02b59-57e0-4114-9a79-343c109342bd.png)
![image](https://user-images.githubusercontent.com/69044307/147694845-298e0d3a-ad19-4ecc-a576-43b4c93cd9ce.png)
![image](https://user-images.githubusercontent.com/69044307/147694846-ac2893d7-d011-4555-bcd7-0d1bb55eb941.png)
![image](https://user-images.githubusercontent.com/69044307/147694848-1f56852d-90a6-486a-995f-a29decec90b7.png)
![image](https://user-images.githubusercontent.com/69044307/147694849-6238ccca-4219-45cd-9723-716eac07e9a9.png)
![image](https://user-images.githubusercontent.com/69044307/147694850-61ffddc8-a557-43fb-84a8-cafd55b2418c.png)
![image](https://user-images.githubusercontent.com/69044307/147694851-48d90327-84a4-46b1-9ede-819564f73abc.png)
![image](https://user-images.githubusercontent.com/69044307/147694852-f11c2572-d70b-44a0-9f53-c8090a918760.png)
![image](https://user-images.githubusercontent.com/69044307/147694853-83b5f0d7-7d07-4dfc-a197-acde5765f9ad.png)
![image](https://user-images.githubusercontent.com/69044307/147694855-8ae6afc8-e558-47d1-9976-5e6d57f9b18b.png)
![image](https://user-images.githubusercontent.com/69044307/147694854-42cbb9ac-2d50-4318-8491-74d44dc26c8b.png)
![image](https://user-images.githubusercontent.com/69044307/147694856-06345284-4dbb-49de-a1d6-d17992e72989.png)
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by DASPELLER4** [comment]
hate speech will not be allowed
